### ISSUE TITLE
Links aren't rendered properly by Docusaurus?

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/BC-wiki#2]
wikilinks not rendered: https://breadcrumbs-wiki.onrender.com/docs/Home
md links not rendered: https://breadcrumbs-wiki.onrender.com/docs/Codeblocks#type

**Comment by SkepticMystic** [comment]
Thanks!
Links are difficult with Docusaurus 🙈 maybe it's just me.
But this should be resolved now

**Comment by chrisgrieser** [comment]
yep, works now!

tbh, I also spent way to much time and trial and error figuring out links in my Shimmering Focus Docs, too 🙈
